auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: itssee
production_url : http://itssee.github.io
me: https://github.com/itssee


author :
  name : itssee
  github : itssee
  
feed: /atom.xml
